// <auto-generated />
namespace EchoDesertTrips.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_numberofcustomers_to_reservation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_numberofcustomers_to_reservation));
        
        string IMigrationMetadata.Id
        {
            get { return "201806011223046_add_numberofcustomers_to_reservation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
