// <auto-generated />
namespace EchoDesertTrips.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix_customer_migration_problem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_customer_migration_problem));
        
        string IMigrationMetadata.Id
        {
            get { return "202004051734492_fix_customer_migration_problem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
