// <auto-generated />
namespace EchoDesertTrips.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tourtypeprice_to_requried : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tourtypeprice_to_requried));
        
        string IMigrationMetadata.Id
        {
            get { return "202005071504338_tourtypeprice_to_requried"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
